### Get List of Movies
GET http://127.0.0.1:8000/movies/

### Get Movie Details
GET http://127.0.0.1:8000/movies/1

### Create a Movie
POST http://127.0.0.1:8000/movies/
Content-Type: application/json

{
    "title": "Inception",
    "director": "Christopher Nolan",
    "year": 2010,
    "description": "A mind-bending thriller about dream infiltration."
}

### Get List of Actors
GET http://127.0.0.1:8000/actors/

### Create an Actor
POST http://127.0.0.1:8000/actors/
Content-Type: application/json

{
    "name": "Leonardo",
    "surname": "DiCaprio"
}

### Add Actor to Movie
POST http://127.0.0.1:8000/movies/1/actors/
Content-Type: application/json

{
    "actor_id": 1
}
